name: Build OpenWrt for Cudy WR3000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils dos2unix zstd

      - name: Download OpenWrt Image Builder (25.12.5)
        run: |
          # Скачиваем реально существующий релиз 25.12.5 для архитектуры mediatek/filogic
          wget https://openwrt.org
          tar --zstd -xf openwrt-imagebuilder-25.12.5-mediatek-filogic.Linux-x86_64.tar.zst
          mv openwrt-imagebuilder-25.12.5-mediatek-filogic.Linux-x86_64 imagebuilder

      - name: Copy and fix custom files
        run: |
          mkdir -p imagebuilder/files
          if [ -d "files" ]; then
            cp -r files/* imagebuilder/files/
            find imagebuilder/files/ -type f -exec dos2unix {} \;
            chmod +x imagebuilder/files/etc/uci-defaults/*
          fi

      - name: Add AmneziaWG Repository
        run: |
          cd imagebuilder
          echo "src/gz amneziawg_repo https://githubusercontent.com" >> repositories.conf

      - name: Compile Firmware
        run: |
          cd imagebuilder
          make image PROFILE=cudy_wr3000s-v1 PACKAGES="luci-i18n-base-ru luci-i18n-adblock-fast-ru ttyd kmod-amneziawg amneziawg-tools" FILES="files/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cudy-WR3000S-Firmware-25.12.5
          path: imagebuilder/bin/targets/mediatek/filogic/*sysupgrade.bin

